language: node_js
node_js:
  - '10'
jobs:
  include:
    - stage: tests
      name: unit tests
      script: npm run test:cov
    - stage: tests
      name: lint
      script: npm run lint
    - stage: tests
      name: e2e
      script: npm run test:e2e
    - stage: tests
      name: build
      script: npm run build
    - stage: deploy
      name: deploy
      script: npm --version
    # - if: branch = master
    #   stage: deploy to staging
    #   script: skip
    #   deploy: heroku
    #     provider: heroku
    #     app: eshop-crawler
    #     api_key: $HEROKU_AUTH_TOKEN
