language: node_js
node_js:
  - '10'
jobs:
  include:
    - stage: tests
      name: unit tests
      script: npm run test:cov
    - stage: tests
      name: lint
      script: npm run lint
    - stage: tests
      name: e2e
      script: npm run test:e2e
      services:
        - postgresql
    - stage: tests
      name: build
      script: npm run build
